apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels: 
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres_user"
  POSTGRES_PASSWORD: "postgres_password"